/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id:
    'us-east-2:9139f0ac-dd80-4bdb-b262-220fe72c7d3b',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_G0Dv7Rfpb',
  aws_user_pools_web_client_id: '3da3fdo70cn7sdsvfcnf57dhcn',
  oauth: {}
}

export default awsmobile
